# Auto-generated by compose2nix.
{...}: {
  flake.nixosModules.podman-spark-bytes = {
    pkgs,
    lib,
    config,
    ...
  }: {
    # Runtime
    virtualisation.podman = {
      enable = true;
      autoPrune.enable = true;
      dockerCompat = true;
    };

    # Enable container name DNS for all Podman networks.
    networking.firewall.interfaces = let
      matchAll =
        if !config.networking.nftables.enable
        then "podman+"
        else "podman*";
    in {
      "${matchAll}".allowedUDPPorts = [53];
    };

    virtualisation.oci-containers.backend = "podman";

    # Containers
    virtualisation.oci-containers.containers."spark-bytebin" = {
      image = "ghcr.io/lucko/bytebin";
      environment = {
        "BYTEBIN_CONTENT_MAXSIZE" = "5";
        "BYTEBIN_MISC_KEYLENGTH" = "15";
      };
      volumes = [
        "spark_data:/var/lib/bytebin/content:rw"
        "spark_db:/var/lib/bytebin/db:rw"
      ];
      ports = [
        "23380:8080/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=bytebin"
        "--network=spark_default"
      ];
    };
    systemd.services."podman-spark-bytebin" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "no";
      };
      after = [
        "podman-network-spark_default.service"
        "podman-volume-spark_data.service"
        "podman-volume-spark_db.service"
      ];
      requires = [
        "podman-network-spark_default.service"
        "podman-volume-spark_data.service"
        "podman-volume-spark_db.service"
      ];
      partOf = ["podman-compose-spark-root.target"];
      wantedBy = ["podman-compose-spark-root.target"];
    };
    virtualisation.oci-containers.containers."spark-bytesocks" = {
      image = "ghcr.io/lucko/bytesocks";
      environment = {
        "BYTESOCKS_MISC_KEYLENGTH" = "15";
        "BYTESOCKS_RATELIMIT_MSG_AMOUNT" = "10000";
      };
      ports = [
        "23381:8080/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=bytesocks"
        "--network=spark_default"
      ];
    };
    systemd.services."podman-spark-bytesocks" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "no";
      };
      after = ["podman-network-spark_default.service"];
      requires = ["podman-network-spark_default.service"];
      partOf = ["podman-compose-spark-root.target"];
      wantedBy = ["podman-compose-spark-root.target"];
    };

    # Networks
    systemd.services."podman-network-spark_default" = {
      path = [pkgs.podman];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f spark_default";
      };
      script = ''
        podman network inspect spark_default || podman network create spark_default
      '';
      partOf = ["podman-compose-spark-root.target"];
      wantedBy = ["podman-compose-spark-root.target"];
    };

    # Volumes
    systemd.services."podman-volume-spark_data" = {
      path = [pkgs.podman];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      script = ''
        podman volume inspect spark_data || podman volume create spark_data
      '';
      partOf = ["podman-compose-spark-root.target"];
      wantedBy = ["podman-compose-spark-root.target"];
    };
    systemd.services."podman-volume-spark_db" = {
      path = [pkgs.podman];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      script = ''
        podman volume inspect spark_db || podman volume create spark_db
      '';
      partOf = ["podman-compose-spark-root.target"];
      wantedBy = ["podman-compose-spark-root.target"];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-spark-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = ["multi-user.target"];
    };
  };
}
