# `carbon` -- Daily driver 14" ThinkPad X1 Carbon Gen 13.
#
# This file contains the NixOS configuration flake module for this machine.
{
  self,
  inputs,
  ...
}: {
  # NixOS system configuration.
  flake.nixosConfigurations.carbon = inputs.nixpkgs.lib.nixosSystem {
    modules = [
      self.nixosModules.carbon
      self.nixosModules.carbon-hardware
    ];

    nix.nixPath = ["nixpkgs=${inputs.nixpkgs}"];
  };

  # Primary NixOS config module.
  flake.nixosModule.carbon = {pkgs, ...}: {
    imports = [
      self.nixosModules.limine # Bootloader.
      self.nixosModules.gnome # Window manager.

      self.nixosModules.username-marked01one
    ];

    # Networking configs.
    networking.networkmanager.enable = true;
    networking.dhcpcd.setHostname = false;
    networking.hostname = "carbon";

    # Set your time zone.
    time.timeZone = "America/Los_Angeles";

    # Select internationalisation properties.
    i18n.defaultLocale = "en_US.UTF-8";

    i18n.extraLocaleSettings = {
      LC_ADDRESS = "en_US.UTF-8";
      LC_IDENTIFICATION = "en_US.UTF-8";
      LC_MEASUREMENT = "en_US.UTF-8";
      LC_MONETARY = "en_US.UTF-8";
      LC_NAME = "en_US.UTF-8";
      LC_NUMERIC = "en_US.UTF-8";
      LC_PAPER = "en_US.UTF-8";
      LC_TELEPHONE = "en_US.UTF-8";
      LC_TIME = "en_US.UTF-8";
    };

    # Enable CUPS to print documents
    services.printing.enable = true;

    # Configure keymap in X11
    services.xserver.xkb.layout = "us";
    services.xserver.xkb.variant = "";

    users.defaultUserShell = pkgs.zsh;

    users.users.marked01one = {
      isNormalUser = true;
      description = "marked01one";
      extraGroups = ["networkmanager" "wheel"];
      shell = pkgs.zsh;
    };
  };

  # Auto-generated hardware config for `carbon`.
  # Do not modify this module!  It was generated by ‘nixos-generate-config’
  # and may be overwritten by future invocations.
  flake.nixosModules.carbon-hardware = {
    config,
    lib,
    modulesPath,
    ...
  }: {
    imports = [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = [
      "xhci_pci"
      "thunderbolt"
      "nvme"
      "usb_storage"
      "sd_mod"
    ];
    boot.initrd.kernelModules = [];
    boot.kernelModules = ["kvm-intel"];
    boot.extraModulePackages = [];

    fileSystems."/" = {
      device = "/dev/disk/by-uuid/77fdd6f3-850e-42f8-bf38-5c53bd54598f";
      fsType = "ext4";
    };

    fileSystems."/boot" = {
      device = "/dev/disk/by-uuid/5399-8EE9";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };

    swapDevices = [];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode =
      lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
