# `carbon` -- Daily driver 14" ThinkPad X1 Carbon Gen 13.
#
# This file contains the NixOS configuration flake module for this machine.
{
  self,
  inputs,
  ...
}: {
  # Import Home Manager input.
  # We're using importing rules specific to `flake-parts`.
  # https://flake.parts/options/home-manager.html
  imports = [inputs.home-manager.flakeModules.home-manager];

  # NixOS system configuration.
  flake.nixosConfigurations.carbon = inputs.nixpkgs.lib.nixosSystem {
    modules = [
      self.nixosModules.carbon
      self.nixosModules.carbon-hardware
    ];
  };

  # Primary NixOS config module.
  flake.nixosModules.carbon = {...}: {
    imports = with self.nixosModules; [
      # Users
      marked01one

      home-manager # Home Manager
      limine # bootloader
      gnome # window manager
      niri
      zsh # shell
      nix-tools # Nix tools
      fonts # Font configs
      fingerprint # Fingerprint support
      laptop # Power configs for laptop
      nix-ld # Enable NixOS to run dynamically-linked executables.

      # Programming languages
      python
      dotnet-sdk

      # Core apps
      vscode
      git
      firefox
      tailscale
      steam
      unityhub
      btop
    ];

    # Networking configs.
    networking.networkmanager.enable = true;
    networking.dhcpcd.setHostname = false;
    networking.hostName = "carbon";

    # Set your time zone.
    time.timeZone = "America/Los_Angeles";

    # Select internationalisation properties.
    i18n.defaultLocale = "en_US.UTF-8";

    i18n.extraLocaleSettings = {
      LC_ADDRESS = "en_US.UTF-8";
      LC_IDENTIFICATION = "en_US.UTF-8";
      LC_MEASUREMENT = "en_US.UTF-8";
      LC_MONETARY = "en_US.UTF-8";
      LC_NAME = "en_US.UTF-8";
      LC_NUMERIC = "en_US.UTF-8";
      LC_PAPER = "en_US.UTF-8";
      LC_TELEPHONE = "en_US.UTF-8";
      LC_TIME = "en_US.UTF-8";
    };

    # Enable CUPS to print documents
    services.printing.enable = true;

    # Configure keymap in X11
    services.xserver.xkb.layout = "us";
    services.xserver.xkb.variant = "";

    # Allow unfree packages
    nixpkgs.config.allowUnfree = true;

    system.stateVersion = "25.11";

    nix = {
      settings = {
        allowed-users = ["marked01one"];
        experimental-features = ["nix-command" "flakes"];
      };
      nixPath = ["nixpkgs=${inputs.nixpkgs}"];
    };
  };

  # Auto-generated hardware config for `carbon`.
  # Do not modify this module!  It was generated by ‘nixos-generate-config’
  # and may be overwritten by future invocations.
  flake.nixosModules.carbon-hardware = {
    pkgs,
    config,
    lib,
    modulesPath,
    ...
  }: {
    imports = [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = [
      "xhci_pci"
      "thunderbolt"
      "nvme"
      "usb_storage"
      "sd_mod"
    ];
    boot.initrd.kernelModules = [];
    boot.kernelModules = ["kvm-intel"];
    boot.extraModulePackages = [];

    fileSystems."/" = {
      device = "/dev/disk/by-uuid/77fdd6f3-850e-42f8-bf38-5c53bd54598f";
      fsType = "ext4";
    };

    fileSystems."/boot" = {
      device = "/dev/disk/by-uuid/5399-8EE9";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };

    swapDevices = [];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode =
      lib.mkDefault config.hardware.enableRedistributableFirmware;

    hardware.graphics = {
      enable = true;
      extraPackages = with pkgs; [
        intel-media-driver
        vpl-gpu-rt
      ];
    };
  };
}
